language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "travis_retry pip install nose"
  - "travis_retry pip install coveralls"
  - "travis_retry pip install --pre -e ."

script: "python setup.py nosetests --with-coverage --cover-package=dukpy --cover-erase"

after_success:
  coveralls
